//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "match_v5", table_name = "bans")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub ban_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub match_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub team_id: i32,
    pub champion_id: i32,
    pub pick_turn: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::teams::Entity",
        from = "(Column::MatchId, Column::TeamId)",
        to = "(super::teams::Column::MatchId, super::teams::Column::TeamId)",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Teams,
}

impl Related<super::teams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Teams.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
