//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "league_v4", table_name = "mini_series")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub puuid: String,
    pub losses: i32,
    #[sea_orm(column_type = "Text")]
    pub progress: String,
    pub target: i32,
    pub wins: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::league_item::Entity",
        from = "Column::Puuid",
        to = "super::league_item::Column::Puuid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    LeagueItem,
}

impl Related<super::league_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LeagueItem.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
