CREATE TYPE clash_v1.player_position AS ENUM('UNSELECTED', 'FILL', 'TOP', 'JUNGLE', 'MIDDLE', 'BOTTOM', 'UTILITY');
CREATE TYPE clash_v1.player_role AS ENUM('CAPTAIN', 'MEMBER');
CREATE TYPE lol_challenges_v1.challenge_config_info_state AS ENUM('DISABLED', 'HIDDEN', 'ENABLED', 'ARCHIVED');
CREATE TYPE lol_challenges_v1.challenge_config_info_tracking AS ENUM('LIFETIME', 'SEASON');
CREATE TYPE lol_status_v4.status_maintenance_underscorestatus AS ENUM('scheduled', 'in_progress', 'complete');
CREATE TYPE lol_status_v4.status_incident_underscoreseverity AS ENUM('info', 'warning', 'critical');
CREATE TYPE match_v5.challenges_faster_support_quest_completion AS ENUM('0', '1');
CREATE TYPE match_v5.challenges_had_afk_teammate AS ENUM('0', '1');
CREATE TYPE match_v5.challenges_highest_crowd_control_score AS ENUM('0', '1');
CREATE TYPE match_v5.challenges_highest_ward_kills AS ENUM('0', '1');
CREATE TYPE match_v5.challenges_laning_phase_gold_exp_advantage AS ENUM('0', '1');
CREATE TYPE match_v5.challenges_played_champ_select_position AS ENUM('0', '1');
CREATE TYPE spectator_v5.featured_game_info_game_mode AS ENUM('CLASSIC', 'ODIN', 'ARAM', 'TUTORIAL', 'ONEFORALL', 'ASCENSION', 'FIRSTBLOOD', 'KINGPORO');
CREATE TYPE spectator_v5.featured_game_info_game_type AS ENUM('CUSTOM_GAME', 'MATCHED_GAME', 'TUTORIAL_GAME');
CREATE TYPE tournament_stub_v5.provider_registration_parameters_v5_region AS ENUM('BR', 'EUNE', 'EUW', 'JP', 'LAN', 'LAS', 'NA', 'OCE', 'PBE', 'RU', 'TR', 'KR');
CREATE TYPE tournament_stub_v5.tournament_code_parameters_v5_pick_type AS ENUM('BLIND_PICK', 'DRAFT_MODE', 'ALL_RANDOM', 'TOURNAMENT_DRAFT');
CREATE TYPE tournament_stub_v5.tournament_code_parameters_v5_map_type AS ENUM('SUMMONERS_RIFT', 'HOWLING_ABYSS');
CREATE TYPE tournament_stub_v5.tournament_code_parameters_v5_spectator_type AS ENUM('NONE', 'LOBBYONLY', 'ALL');
CREATE TYPE tournament_stub_v5.tournament_code_v5_region AS ENUM('BR', 'EUNE', 'EUW', 'JP', 'LAN', 'LAS', 'NA', 'OCE', 'PBE', 'RU', 'TR', 'KR');
CREATE TYPE tournament_v5.provider_registration_parameters_v5_region AS ENUM('BR', 'EUNE', 'EUW', 'JP', 'LAN', 'LAS', 'NA', 'OCE', 'PBE', 'RU', 'TR', 'KR', 'PH', 'SG', 'TH', 'TW', 'VN');
CREATE TYPE tournament_v5.tournament_code_parameters_v5_pick_type AS ENUM('BLIND_PICK', 'DRAFT_MODE', 'ALL_RANDOM', 'TOURNAMENT_DRAFT');
CREATE TYPE tournament_v5.tournament_code_parameters_v5_map_type AS ENUM('SUMMONERS_RIFT', 'HOWLING_ABYSS');
CREATE TYPE tournament_v5.tournament_code_parameters_v5_spectator_type AS ENUM('NONE', 'LOBBYONLY', 'ALL');
CREATE TYPE tournament_v5.tournament_code_update_parameters_v5_pick_type AS ENUM('BLIND_PICK', 'DRAFT_MODE', 'ALL_RANDOM', 'TOURNAMENT_DRAFT');
CREATE TYPE tournament_v5.tournament_code_update_parameters_v5_map_type AS ENUM('SUMMONERS_RIFT', 'HOWLING_ABYSS');
CREATE TYPE tournament_v5.tournament_code_update_parameters_v5_spectator_type AS ENUM('NONE', 'LOBBYONLY', 'ALL');
CREATE TYPE tournament_v5.tournament_code_v5_region AS ENUM('BR', 'EUNE', 'EUW', 'JP', 'LAN', 'LAS', 'NA', 'OCE', 'PBE', 'RU', 'TR', 'KR', 'PH', 'SG', 'TH', 'TW', 'VN');
