CREATE TABLE match_v5.challenges
(
    match_id                                          TEXT    NOT NULL,
    participant_id                                    INTEGER NOT NULL,

    x12_assist_streak_count                           INTEGER,
    baron_buff_gold_advantage_over_threshold          INTEGER,
    control_ward_time_coverage_in_river_or_enemy_half REAL,
    earliest_baron                                    DOUBLE PRECISION,
    earliest_dragon_takedown                          DOUBLE PRECISION,
    earliest_elder_dragon                             DOUBLE PRECISION,
    early_laning_phase_gold_exp_advantage             DOUBLE PRECISION,
    faster_support_quest_completion                   INTEGER, -- enum: 0 or 1
    fastest_legendary                                 DOUBLE PRECISION,
    had_afk_teammate                                  INTEGER, -- enum: 0 or 1
    highest_champion_damage                           INTEGER,
    highest_crowd_control_score                       INTEGER, -- enum: 0 or 1
    highest_ward_kills                                INTEGER, -- enum: 0 or 1
    jungler_kills_early_jungle                        INTEGER,
    kills_on_laners_early_jungle_as_jungler           INTEGER,
    laning_phase_gold_exp_advantage                   INTEGER, -- enum: 0 or 1
    legendary_count                                   INTEGER,
    max_cs_advantage_on_lane_opponent                 REAL,
    max_level_lead_lane_opponent                      INTEGER,
    most_wards_destroyed_one_sweeper                  INTEGER,
    mythic_item_used                                  INTEGER,
    played_champ_select_position                      INTEGER, -- enum: 0 or 1
    solo_turrets_lategame                             INTEGER,
    takedowns_first25_minutes                         INTEGER,
    teleport_takedowns                                INTEGER,
    third_inhibitor_destroyed_time                    DOUBLE PRECISION,
    three_wards_one_sweeper_count                     INTEGER,
    vision_score_advantage_lane_opponent              REAL,
    infernal_scale_pickup                             INTEGER,
    fist_bump_participation                           INTEGER,
    void_monster_kill                                 INTEGER,
    ability_uses                                      INTEGER,
    aces_before15_minutes                             INTEGER,
    allied_jungle_monster_kills                       REAL,
    baron_takedowns                                   INTEGER,
    blast_cone_opposite_opponent_count                INTEGER,
    bounty_gold                                       DOUBLE PRECISION,
    buffs_stolen                                      INTEGER,
    complete_support_quest_in_time                    INTEGER,
    control_wards_placed                              INTEGER,
    damage_per_minute                                 REAL,
    damage_taken_on_team_percentage                   REAL,
    danced_with_rift_herald                           INTEGER,
    deaths_by_enemy_champs                            INTEGER,
    dodge_skill_shots_small_window                    INTEGER,
    double_aces                                       INTEGER,
    dragon_takedowns                                  INTEGER,
    legendary_item_used                               INTEGER[],
    effective_heal_and_shielding                      REAL,
    elder_dragon_kills_with_opposing_soul             INTEGER,
    elder_dragon_multikills                           INTEGER,
    enemy_champion_immobilizations                    INTEGER,
    enemy_jungle_monster_kills                        REAL,
    epic_monster_kills_near_enemy_jungler             INTEGER,
    epic_monster_kills_within30_seconds_of_spawn      INTEGER,
    epic_monster_steals                               INTEGER,
    epic_monster_stolen_without_smite                 INTEGER,
    first_turret_killed                               DOUBLE PRECISION,
    first_turret_killed_time                          REAL,
    flawless_aces                                     INTEGER,
    full_team_takedown                                INTEGER,
    game_length                                       REAL,
    get_takedowns_in_all_lanes_early_jungle_as_laner  INTEGER,
    gold_per_minute                                   REAL,
    had_open_nexus                                    INTEGER,
    immobilize_and_kill_with_ally                     INTEGER,
    initial_buff_count                                INTEGER,
    initial_crab_count                                INTEGER,
    jungle_cs_before10_minutes                        REAL,
    jungler_takedowns_near_damaged_epic_monster       INTEGER,
    kda                                               REAL,
    kill_after_hidden_with_ally                       INTEGER,
    killed_champ_took_full_team_damage_survived       INTEGER,
    killing_sprees                                    INTEGER,
    kill_participation                                REAL,
    kills_near_enemy_turret                           INTEGER,
    kills_on_other_lanes_early_jungle_as_laner        INTEGER,
    kills_on_recently_healed_by_aram_pack             INTEGER,
    kills_under_own_turret                            INTEGER,
    kills_with_help_from_epic_monster                 INTEGER,
    knock_enemy_into_team_and_kill                    INTEGER,
    k_turrets_destroyed_before_plates_fall            INTEGER,
    land_skill_shots_early_game                       INTEGER,
    lane_minions_first10_minutes                      INTEGER,
    lost_an_inhibitor                                 INTEGER,
    max_kill_deficit                                  INTEGER,
    mejais_full_stack_in_time                         INTEGER,
    more_enemy_jungle_than_opponent                   REAL,
    multi_kill_one_spell                              INTEGER,
    multikills                                        INTEGER,
    multikills_after_aggressive_flash                 INTEGER,
    multi_turret_rift_herald_count                    INTEGER,
    outer_turret_executes_before10_minutes            INTEGER,
    outnumbered_kills                                 INTEGER,
    outnumbered_nexus_kill                            INTEGER,
    perfect_dragon_souls_taken                        INTEGER,
    perfect_game                                      INTEGER,
    pick_kill_with_ally                               INTEGER,
    poro_explosions                                   INTEGER,
    quick_cleanse                                     INTEGER,
    quick_first_turret                                INTEGER,
    quick_solo_kills                                  INTEGER,
    rift_herald_takedowns                             INTEGER,
    save_ally_from_death                              INTEGER,
    scuttle_crab_kills                                INTEGER,
    shortest_time_to_ace_from_first_takedown          REAL,
    skillshots_dodged                                 INTEGER,
    skillshots_hit                                    INTEGER,
    snowballs_hit                                     INTEGER,
    solo_baron_kills                                  INTEGER,
    SWARM_DefeatAatrox                                INTEGER,
    SWARM_DefeatBriar                                 INTEGER,
    SWARM_DefeatMiniBosses                            INTEGER,
    SWARM_EvolveWeapon                                INTEGER,
    SWARM_Have3Passives                               INTEGER,
    SWARM_KillEnemy                                   INTEGER,
    SWARM_PickupGold                                  REAL,
    SWARM_ReachLevel50                                INTEGER,
    SWARM_Survive15Min                                INTEGER,
    SWARM_WinWith5EvolvedWeapons                      INTEGER,
    solo_kills                                        INTEGER,
    stealth_wards_placed                              INTEGER,
    survived_single_digit_hp_count                    INTEGER,
    survived_three_immobilizes_in_fight               INTEGER,
    takedown_on_first_turret                          INTEGER,
    takedowns                                         INTEGER,
    takedowns_after_gaining_level_advantage           INTEGER,
    takedowns_before_jungle_minion_spawn              INTEGER,
    takedowns_first_x_minutes                         INTEGER,
    takedowns_in_alcove                               INTEGER,
    takedowns_in_enemy_fountain                       INTEGER,
    team_baron_kills                                  INTEGER,
    team_damage_percentage                            REAL,
    team_elder_dragon_kills                           INTEGER,
    team_rift_herald_kills                            INTEGER,
    took_large_damage_survived                        INTEGER,
    turret_plates_taken                               INTEGER,
    turrets_taken_with_rift_herald                    INTEGER,
    turret_takedowns                                  INTEGER,
    twenty_minions_in3_seconds_count                  INTEGER,
    two_wards_one_sweeper_count                       INTEGER,
    unseen_recalls                                    INTEGER,
    vision_score_per_minute                           REAL,
    wards_guarded                                     INTEGER,
    ward_takedowns                                    INTEGER,
    ward_takedowns_before20m                          INTEGER,
    heal_from_map_sources                             DOUBLE PRECISION,

    PRIMARY KEY (match_id, participant_id),
    FOREIGN KEY (match_id, participant_id)
        REFERENCES match_v5.participant (match_id, participant_id)
);

COMMENT ON TABLE match_v5.challenges IS 'Challenges DTO';
COMMENT ON COLUMN match_v5.challenges.multi_kill_one_spell IS 'This is an offshoot of the OneStone challenge. The code checks if a spell with the same instance ID does the final point of damage to at least 2 Champions. It doesn''t matter if they''re enemies, but you cannot hurt your friends.';
COMMENT ON COLUMN match_v5.challenges.turrets_taken_with_rift_herald IS 'Any player who damages a tower that is destroyed within 30 seconds of a Rift Herald charge will receive credit. A player who does not damage the tower will not receive credit.';
