// use anyhow::Result;
// use riven::models::match_v5::Challenges;
// use sqlx::{PgPool, QueryBuilder};
//
// /// Inserts a Challenges record into the match_v5.challenges table for a
// given /// match and participant.
// pub async fn insert_challenges(
//     pool: &PgPool,
//     match_id: &str,
//     participant_id: i32,
//     challenges: &Challenges,
// ) -> Result<(), sqlx::Error> {
//     let mut qb = QueryBuilder::new(
//         r#"
// INSERT INTO match_v5.challenges (
//     match_id,
//     participant_id,
//     x12_assist_streak_count,
//     baron_buff_gold_advantage_over_threshold,
//     control_ward_time_coverage_in_river_or_enemy_half,
//     earliest_baron,
//     earliest_dragon_takedown,
//     earliest_elder_dragon,
//     early_laning_phase_gold_exp_advantage,
//     faster_support_quest_completion,
//     fastest_legendary,
//     had_afk_teammate,
//     highest_champion_damage,
//     highest_crowd_control_score,
//     highest_ward_kills,
//     jungler_kills_early_jungle,
//     kills_on_laners_early_jungle_as_jungler,
//     laning_phase_gold_exp_advantage,
//     legendary_count,
//     max_cs_advantage_on_lane_opponent,
//     max_level_lead_lane_opponent,
//     most_wards_destroyed_one_sweeper,
//     mythic_item_used,
//     played_champ_select_position,
//     solo_turrets_lategame,
//     takedowns_first25_minutes,
//     teleport_takedowns,
//     third_inhibitor_destroyed_time,
//     three_wards_one_sweeper_count,
//     vision_score_advantage_lane_opponent,
//     infernal_scale_pickup,
//     fist_bump_participation,
//     void_monster_kill,
//     ability_uses,
//     aces_before15_minutes,
//     allied_jungle_monster_kills,
//     baron_takedowns,
//     blast_cone_opposite_opponent_count,
//     bounty_gold,
//     buffs_stolen,
//     complete_support_quest_in_time,
//     control_wards_placed,
//     damage_per_minute,
//     damage_taken_on_team_percentage,
//     danced_with_rift_herald,
//     deaths_by_enemy_champs,
//     dodge_skill_shots_small_window,
//     double_aces,
//     dragon_takedowns,
//     legendary_item_used,
//     effective_heal_and_shielding,
//     elder_dragon_kills_with_opposing_soul,
//     elder_dragon_multikills,
//     enemy_champion_immobilizations,
//     enemy_jungle_monster_kills,
//     epic_monster_kills_near_enemy_jungler,
//     epic_monster_kills_within30_seconds_of_spawn,
//     epic_monster_steals,
//     epic_monster_stolen_without_smite,
//     first_turret_killed,
//     first_turret_killed_time,
//     flawless_aces,
//     full_team_takedown,
//     game_length,
//     get_takedowns_in_all_lanes_early_jungle_as_laner,
//     gold_per_minute,
//     had_open_nexus,
//     immobilize_and_kill_with_ally,
//     initial_buff_count,
//     initial_crab_count,
//     jungle_cs_before10_minutes,
//     jungler_takedowns_near_damaged_epic_monster,
//     kda,
//     kill_after_hidden_with_ally,
//     killed_champ_took_full_team_damage_survived,
//     killing_sprees,
//     kill_participation,
//     kills_near_enemy_turret,
//     kills_on_other_lanes_early_jungle_as_laner,
//     kills_on_recently_healed_by_aram_pack,
//     kills_under_own_turret,
//     kills_with_help_from_epic_monster,
//     knock_enemy_into_team_and_kill,
//     k_turrets_destroyed_before_plates_fall,
//     land_skill_shots_early_game,
//     lane_minions_first10_minutes,
//     lost_an_inhibitor,
//     max_kill_deficit,
//     mejais_full_stack_in_time,
//     more_enemy_jungle_than_opponent,
//     multi_kill_one_spell,
//     multikills,
//     multikills_after_aggressive_flash,
//     multi_turret_rift_herald_count,
//     outer_turret_executes_before10_minutes,
//     outnumbered_kills,
//     outnumbered_nexus_kill,
//     perfect_dragon_souls_taken,
//     perfect_game,
//     pick_kill_with_ally,
//     poro_explosions,
//     quick_cleanse,
//     quick_first_turret,
//     quick_solo_kills,
//     rift_herald_takedowns,
//     save_ally_from_death,
//     scuttle_crab_kills,
//     shortest_time_to_ace_from_first_takedown,
//     skillshots_dodged,
//     skillshots_hit,
//     snowballs_hit,
//     solo_baron_kills,
//     swarm_defeat_aatrox,
//     swarm_defeat_briar,
//     swarm_defeat_minibosses,
//     swarm_evolve_weapon,
//     swarm_have3_passives,
//     swarm_kill_enemy,
//     swarm_pickup_gold,
//     swarm_reach_level50,
//     swarm_survive15_min,
//     swarm_win_with5_evolved_weapons,
//     solo_kills,
//     stealth_wards_placed,
//     survived_single_digit_hp_count,
//     survived_three_immobilizes_in_fight,
//     takedown_on_first_turret,
//     takedowns,
//     takedowns_after_gaining_level_advantage,
//     takedowns_before_jungle_minion_spawn,
//     takedowns_first_x_minutes,
//     takedowns_in_alcove,
//     takedowns_in_enemy_fountain,
//     team_baron_kills,
//     team_damage_percentage,
//     team_elder_dragon_kills,
//     team_rift_herald_kills,
//     took_large_damage_survived,
//     turret_plates_taken,
//     turrets_taken_with_rift_herald,
//     turret_takedowns,
//     twenty_minions_in3_seconds_count,
//     two_wards_one_sweeper_count,
//     unseen_recalls,
//     vision_score_per_minute,
//     wards_guarded,
//     ward_takedowns,
//     ward_takedowns_before20m,
//     heal_from_map_sources
// ) "#,
//     );
//
//     // Use push_values to insert a single challenges record.
//     qb.push_values([challenges], |mut b, ch| {
//         b.push_bind(match_id)
//             .push_bind(participant_id)
//             .push_bind(ch.x12_assist_streak_count)
//             .push_bind(ch.baron_buff_gold_advantage_over_threshold)
//             .push_bind(ch.control_ward_time_coverage_in_river_or_enemy_half)
//             .push_bind(ch.earliest_baron)
//             .push_bind(ch.earliest_dragon_takedown)
//             .push_bind(ch.earliest_elder_dragon)
//             .push_bind(ch.early_laning_phase_gold_exp_advantage)
//             .push_bind(ch.faster_support_quest_completion)
//             .push_bind(ch.fastest_legendary)
//             .push_bind(ch.had_afk_teammate)
//             .push_bind(ch.highest_champion_damage)
//             .push_bind(ch.highest_crowd_control_score)
//             .push_bind(ch.highest_ward_kills)
//             .push_bind(ch.jungler_kills_early_jungle)
//             .push_bind(ch.kills_on_laners_early_jungle_as_jungler)
//             .push_bind(ch.laning_phase_gold_exp_advantage)
//             .push_bind(ch.legendary_count)
//             .push_bind(ch.max_cs_advantage_on_lane_opponent)
//             .push_bind(ch.max_level_lead_lane_opponent)
//             .push_bind(ch.most_wards_destroyed_one_sweeper)
//             .push_bind(ch.mythic_item_used)
//             .push_bind(ch.played_champ_select_position)
//             .push_bind(ch.solo_turrets_lategame)
//             .push_bind(ch.takedowns_first25_minutes)
//             .push_bind(ch.teleport_takedowns)
//             .push_bind(ch.third_inhibitor_destroyed_time)
//             .push_bind(ch.three_wards_one_sweeper_count)
//             .push_bind(ch.vision_score_advantage_lane_opponent)
//             .push_bind(ch.infernal_scale_pickup)
//             .push_bind(ch.fist_bump_participation)
//             .push_bind(ch.void_monster_kill)
//             .push_bind(ch.ability_uses)
//             .push_bind(ch.aces_before15_minutes)
//             .push_bind(ch.allied_jungle_monster_kills)
//             .push_bind(ch.baron_takedowns)
//             .push_bind(ch.blast_cone_opposite_opponent_count)
//             .push_bind(ch.bounty_gold)
//             .push_bind(ch.buffs_stolen)
//             .push_bind(ch.complete_support_quest_in_time)
//             .push_bind(ch.control_wards_placed)
//             .push_bind(ch.damage_per_minute)
//             .push_bind(ch.damage_taken_on_team_percentage)
//             .push_bind(ch.danced_with_rift_herald)
//             .push_bind(ch.deaths_by_enemy_champs)
//             .push_bind(ch.dodge_skill_shots_small_window)
//             .push_bind(ch.double_aces)
//             .push_bind(ch.dragon_takedowns)
//             .push_bind(ch.legendary_item_used)
//             .push_bind(ch.effective_heal_and_shielding)
//             .push_bind(ch.elder_dragon_kills_with_opposing_soul)
//             .push_bind(ch.elder_dragon_multikills)
//             .push_bind(ch.enemy_champion_immobilizations)
//             .push_bind(ch.enemy_jungle_monster_kills)
//             .push_bind(ch.epic_monster_kills_near_enemy_jungler)
//             .push_bind(ch.epic_monster_kills_within30_seconds_of_spawn)
//             .push_bind(ch.epic_monster_steals)
//             .push_bind(ch.epic_monster_stolen_without_smite)
//             .push_bind(ch.first_turret_killed)
//             .push_bind(ch.first_turret_killed_time)
//             .push_bind(ch.flawless_aces)
//             .push_bind(ch.full_team_takedown)
//             .push_bind(ch.game_length)
//             .push_bind(ch.get_takedowns_in_all_lanes_early_jungle_as_laner)
//             .push_bind(ch.gold_per_minute)
//             .push_bind(ch.had_open_nexus)
//             .push_bind(ch.immobilize_and_kill_with_ally)
//             .push_bind(ch.initial_buff_count)
//             .push_bind(ch.initial_crab_count)
//             .push_bind(ch.jungle_cs_before10_minutes)
//             .push_bind(ch.jungler_takedowns_near_damaged_epic_monster)
//             .push_bind(ch.kda)
//             .push_bind(ch.kill_after_hidden_with_ally)
//             .push_bind(ch.killed_champ_took_full_team_damage_survived)
//             .push_bind(ch.killing_sprees)
//             .push_bind(ch.kill_participation)
//             .push_bind(ch.kills_near_enemy_turret)
//             .push_bind(ch.kills_on_other_lanes_early_jungle_as_laner)
//             .push_bind(ch.kills_on_recently_healed_by_aram_pack)
//             .push_bind(ch.kills_under_own_turret)
//             .push_bind(ch.kills_with_help_from_epic_monster)
//             .push_bind(ch.knock_enemy_into_team_and_kill)
//             .push_bind(ch.k_turrets_destroyed_before_plates_fall)
//             .push_bind(ch.land_skill_shots_early_game)
//             .push_bind(ch.lane_minions_first10_minutes)
//             .push_bind(ch.lost_an_inhibitor)
//             .push_bind(ch.max_kill_deficit)
//             .push_bind(ch.mejais_full_stack_in_time)
//             .push_bind(ch.more_enemy_jungle_than_opponent)
//             .push_bind(ch.multi_kill_one_spell)
//             .push_bind(ch.multikills)
//             .push_bind(ch.multikills_after_aggressive_flash)
//             .push_bind(ch.multi_turret_rift_herald_count)
//             .push_bind(ch.outer_turret_executes_before10_minutes)
//             .push_bind(ch.outnumbered_kills)
//             .push_bind(ch.outnumbered_nexus_kill)
//             .push_bind(ch.perfect_dragon_souls_taken)
//             .push_bind(ch.perfect_game)
//             .push_bind(ch.pick_kill_with_ally)
//             .push_bind(ch.poro_explosions)
//             .push_bind(ch.quick_cleanse)
//             .push_bind(ch.quick_first_turret)
//             .push_bind(ch.quick_solo_kills)
//             .push_bind(ch.rift_herald_takedowns)
//             .push_bind(ch.save_ally_from_death)
//             .push_bind(ch.scuttle_crab_kills)
//             .push_bind(ch.shortest_time_to_ace_from_first_takedown)
//             .push_bind(ch.skillshots_dodged)
//             .push_bind(ch.skillshots_hit)
//             .push_bind(ch.snowballs_hit)
//             .push_bind(ch.solo_baron_kills)
//             .push_bind(ch.swarm_defeat_aatrox)
//             .push_bind(ch.swarm_defeat_briar)
//             .push_bind(ch.swarm_defeat_mini_bosses)
//             .push_bind(ch.swarm_evolve_weapon)
//             .push_bind(ch.swarm_have3_passives)
//             .push_bind(ch.swarm_kill_enemy)
//             .push_bind(ch.swarm_pickup_gold)
//             .push_bind(ch.swarm_reach_level50)
//             .push_bind(ch.swarm_survive15_min)
//             .push_bind(ch.swarm_win_with5_evolved_weapons)
//             .push_bind(ch.solo_kills)
//             .push_bind(ch.stealth_wards_placed)
//             .push_bind(ch.survived_single_digit_hp_count)
//             .push_bind(ch.survived_three_immobilizes_in_fight)
//             .push_bind(ch.takedown_on_first_turret)
//             .push_bind(ch.takedowns)
//             .push_bind(ch.takedowns_after_gaining_level_advantage)
//             .push_bind(ch.takedowns_before_jungle_minion_spawn)
//             .push_bind(ch.takedowns_first_x_minutes)
//             .push_bind(ch.takedowns_in_alcove)
//             .push_bind(ch.takedowns_in_enemy_fountain)
//             .push_bind(ch.team_baron_kills)
//             .push_bind(ch.team_damage_percentage)
//             .push_bind(ch.team_elder_dragon_kills)
//             .push_bind(ch.team_rift_herald_kills)
//             .push_bind(ch.took_large_damage_survived)
//             .push_bind(ch.turret_plates_taken)
//             .push_bind(ch.turrets_taken_with_rift_herald)
//             .push_bind(ch.turret_takedowns)
//             .push_bind(ch.twenty_minions_in3_seconds_count)
//             .push_bind(ch.two_wards_one_sweeper_count)
//             .push_bind(ch.unseen_recalls)
//             .push_bind(ch.vision_score_per_minute)
//             .push_bind(ch.wards_guarded)
//             .push_bind(ch.ward_takedowns)
//             .push_bind(ch.ward_takedowns_before20_m)
//             .push_bind(ch.heal_from_map_sources);
//     });
//
//     qb.build().execute(pool).await?;
//     Ok(())
// }
