//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{
    ChallengesFasterSupportQuestCompletion, ChallengesHadAfkTeammate, ChallengesHighestCrowdControlScore,
    ChallengesHighestWardKills, ChallengesLaningPhaseGoldExpAdvantage, ChallengesPlayedChampSelectPosition,
};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "match_v5", table_name = "challenges")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub match_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub participant_id: i32,
    pub x_12_assist_streak_count: Option<i32>,
    pub baron_buff_gold_advantage_over_threshold: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub control_ward_time_coverage_in_river_or_enemy_half: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub earliest_baron: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub earliest_dragon_takedown: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub earliest_elder_dragon: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub early_laning_phase_gold_exp_advantage: Option<Decimal>,
    pub faster_support_quest_completion: Option<ChallengesFasterSupportQuestCompletion>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub fastest_legendary: Option<Decimal>,
    pub had_afk_teammate: Option<ChallengesHadAfkTeammate>,
    pub highest_champion_damage: Option<i32>,
    pub highest_crowd_control_score: Option<ChallengesHighestCrowdControlScore>,
    pub highest_ward_kills: Option<ChallengesHighestWardKills>,
    pub jungler_kills_early_jungle: Option<i32>,
    pub kills_on_laners_early_jungle_as_jungler: Option<i32>,
    pub laning_phase_gold_exp_advantage: Option<ChallengesLaningPhaseGoldExpAdvantage>,
    pub legendary_count: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub max_cs_advantage_on_lane_opponent: Option<Decimal>,
    pub max_level_lead_lane_opponent: Option<i32>,
    pub most_wards_destroyed_one_sweeper: Option<i32>,
    pub mythic_item_used: Option<i32>,
    pub played_champ_select_position: Option<ChallengesPlayedChampSelectPosition>,
    pub solo_turrets_lategame: Option<i32>,
    pub takedowns_first25_minutes: Option<i32>,
    pub teleport_takedowns: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub third_inhibitor_destroyed_time: Option<Decimal>,
    pub three_wards_one_sweeper_count: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub vision_score_advantage_lane_opponent: Option<Decimal>,
    pub infernal_scale_pickup: Option<i32>,
    pub fist_bump_participation: Option<i32>,
    pub void_monster_kill: Option<i32>,
    pub ability_uses: Option<i32>,
    pub aces_before15_minutes: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub allied_jungle_monster_kills: Option<Decimal>,
    pub baron_takedowns: Option<i32>,
    pub blast_cone_opposite_opponent_count: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub bounty_gold: Option<Decimal>,
    pub buffs_stolen: Option<i32>,
    pub complete_support_quest_in_time: Option<i32>,
    pub control_wards_placed: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub damage_per_minute: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub damage_taken_on_team_percentage: Option<Decimal>,
    pub danced_with_rift_herald: Option<i32>,
    pub deaths_by_enemy_champs: Option<i32>,
    pub dodge_skill_shots_small_window: Option<i32>,
    pub double_aces: Option<i32>,
    pub dragon_takedowns: Option<i32>,
    pub legendary_item_used: Option<Json>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub effective_heal_and_shielding: Option<Decimal>,
    pub elder_dragon_kills_with_opposing_soul: Option<i32>,
    pub elder_dragon_multikills: Option<i32>,
    pub enemy_champion_immobilizations: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub enemy_jungle_monster_kills: Option<Decimal>,
    pub epic_monster_kills_near_enemy_jungler: Option<i32>,
    pub epic_monster_kills_within30_seconds_of_spawn: Option<i32>,
    pub epic_monster_steals: Option<i32>,
    pub epic_monster_stolen_without_smite: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub first_turret_killed: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub first_turret_killed_time: Option<Decimal>,
    pub flawless_aces: Option<i32>,
    pub full_team_takedown: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub game_length: Option<Decimal>,
    pub get_takedowns_in_all_lanes_early_jungle_as_laner: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub gold_per_minute: Option<Decimal>,
    pub had_open_nexus: Option<i32>,
    pub immobilize_and_kill_with_ally: Option<i32>,
    pub initial_buff_count: Option<i32>,
    pub initial_crab_count: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub jungle_cs_before10_minutes: Option<Decimal>,
    pub jungler_takedowns_near_damaged_epic_monster: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub kda: Option<Decimal>,
    pub kill_after_hidden_with_ally: Option<i32>,
    pub killed_champ_took_full_team_damage_survived: Option<i32>,
    pub killing_sprees: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub kill_participation: Option<Decimal>,
    pub kills_near_enemy_turret: Option<i32>,
    pub kills_on_other_lanes_early_jungle_as_laner: Option<i32>,
    pub kills_on_recently_healed_by_aram_pack: Option<i32>,
    pub kills_under_own_turret: Option<i32>,
    pub kills_with_help_from_epic_monster: Option<i32>,
    pub knock_enemy_into_team_and_kill: Option<i32>,
    pub k_turrets_destroyed_before_plates_fall: Option<i32>,
    pub land_skill_shots_early_game: Option<i32>,
    pub lane_minions_first10_minutes: Option<i32>,
    pub lost_an_inhibitor: Option<i32>,
    pub max_kill_deficit: Option<i32>,
    pub mejais_full_stack_in_time: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub more_enemy_jungle_than_opponent: Option<Decimal>,
    pub multi_kill_one_spell: Option<i32>,
    pub multikills: Option<i32>,
    pub multikills_after_aggressive_flash: Option<i32>,
    pub multi_turret_rift_herald_count: Option<i32>,
    pub outer_turret_executes_before10_minutes: Option<i32>,
    pub outnumbered_kills: Option<i32>,
    pub outnumbered_nexus_kill: Option<i32>,
    pub perfect_dragon_souls_taken: Option<i32>,
    pub perfect_game: Option<i32>,
    pub pick_kill_with_ally: Option<i32>,
    pub poro_explosions: Option<i32>,
    pub quick_cleanse: Option<i32>,
    pub quick_first_turret: Option<i32>,
    pub quick_solo_kills: Option<i32>,
    pub rift_herald_takedowns: Option<i32>,
    pub save_ally_from_death: Option<i32>,
    pub scuttle_crab_kills: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub shortest_time_to_ace_from_first_takedown: Option<Decimal>,
    pub skillshots_dodged: Option<i32>,
    pub skillshots_hit: Option<i32>,
    pub snowballs_hit: Option<i32>,
    pub solo_baron_kills: Option<i32>,
    pub swarm_defeat_aatrox: Option<i32>,
    pub swarm_defeat_briar: Option<i32>,
    pub swarm_defeat_mini_bosses: Option<i32>,
    pub swarm_evolve_weapon: Option<i32>,
    pub swarm_have3_passives: Option<i32>,
    pub swarm_kill_enemy: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub swarm_pickup_gold: Option<Decimal>,
    pub swarm_reach_level50: Option<i32>,
    pub swarm_survive15_min: Option<i32>,
    pub swarm_win_with5_evolved_weapons: Option<i32>,
    pub solo_kills: Option<i32>,
    pub stealth_wards_placed: Option<i32>,
    pub survived_single_digit_hp_count: Option<i32>,
    pub survived_three_immobilizes_in_fight: Option<i32>,
    pub takedown_on_first_turret: Option<i32>,
    pub takedowns: Option<i32>,
    pub takedowns_after_gaining_level_advantage: Option<i32>,
    pub takedowns_before_jungle_minion_spawn: Option<i32>,
    pub takedowns_first_x_minutes: Option<i32>,
    pub takedowns_in_alcove: Option<i32>,
    pub takedowns_in_enemy_fountain: Option<i32>,
    pub team_baron_kills: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub team_damage_percentage: Option<Decimal>,
    pub team_elder_dragon_kills: Option<i32>,
    pub team_rift_herald_kills: Option<i32>,
    pub took_large_damage_survived: Option<i32>,
    pub turret_plates_taken: Option<i32>,
    pub turrets_taken_with_rift_herald: Option<i32>,
    pub turret_takedowns: Option<i32>,
    pub twenty_minions_in3_seconds_count: Option<i32>,
    pub two_wards_one_sweeper_count: Option<i32>,
    pub unseen_recalls: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub vision_score_per_minute: Option<Decimal>,
    pub wards_guarded: Option<i32>,
    pub ward_takedowns: Option<i32>,
    pub ward_takedowns_before20_m: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((20, 9)))", nullable)]
    pub heal_from_map_sources: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::participants::Entity",
        from = "(Column::MatchId, Column::ParticipantId)",
        to = "(super::participants::Column::MatchId, super::participants::Column::ParticipantId)",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Participants,
}

impl Related<super::participants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Participants.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
