//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "match_v5", table_name = "perk_style_selections")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub perk_style_selection_id: i32,
    pub perk_style_id: i32,
    pub perk: i32,
    pub var1: i32,
    pub var2: i32,
    pub var3: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::perk_styles::Entity",
        from = "Column::PerkStyleId",
        to = "super::perk_styles::Column::PerkStyleId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PerkStyles,
}

impl Related<super::perk_styles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PerkStyles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
