//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "match_v5", table_name = "teams")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub match_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub team_id: i32,
    pub win: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bans::Entity")]
    Bans,
    #[sea_orm(has_one = "super::feats::Entity")]
    Feats,
    #[sea_orm(
        belongs_to = "super::matches::Entity",
        from = "Column::MatchId",
        to = "super::matches::Column::MatchId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Matches,
    #[sea_orm(has_one = "super::objectives::Entity")]
    Objectives,
}

impl Related<super::bans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bans.def()
    }
}

impl Related<super::feats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Feats.def()
    }
}

impl Related<super::matches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Matches.def()
    }
}

impl Related<super::objectives::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Objectives.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
