//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "account_v1", table_name = "accounts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub puuid: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub game_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tag_line: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub region: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
