//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "match_v5", table_name = "damage_stats")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub frame_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub participant_id: i32,
    pub magic_damage_done: i32,
    pub magic_damage_done_to_champions: i32,
    pub magic_damage_taken: i32,
    pub physical_damage_done: i32,
    pub physical_damage_done_to_champions: i32,
    pub physical_damage_taken: i32,
    pub total_damage_done: i32,
    pub total_damage_done_to_champions: i32,
    pub total_damage_taken: i32,
    pub true_damage_done: i32,
    pub true_damage_done_to_champions: i32,
    pub true_damage_taken: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::timeline_participant_frames::Entity",
        from = "(Column::FrameId, Column::ParticipantId)",
        to = "(super::timeline_participant_frames::Column::FrameId, super::timeline_participant_frames::Column::ParticipantId)",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TimelineParticipantFrames,
}

impl Related<super::timeline_participant_frames::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TimelineParticipantFrames.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
