//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "damage_direction")]
pub enum DamageDirection {
    #[sea_orm(string_value = "dealt")]
    Dealt,
    #[sea_orm(string_value = "received")]
    Received,
}
